# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - karma-path

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      - name: Set up environment variables
        run: |
          echo "DB_URL=${{ secrets.AZURE_SQL_JDBC_URL }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.AZURE_SQL_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.AZURE_SQL_PASSWORD }}" >> $GITHUB_ENV

      - name: Check Azure SQL DB connection
        run: |
          echo "Checking database connection..."
          java -cp .:/home/runner/work/karma-path-srvc/karma-path-srvc/target/*:/home/runner/work/karma-path-srvc/karma-path-srvc/target/lib/* com.microsoft.sqlserver.jdbc.SQLServerDriver
          if [ $? -eq 0 ]; then
            echo "Database connection successful"
          else
            echo "Database connection failed"
            exit 1
          fi

      - name: Upload Test Results
        if: always()  # Run this step even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'karma-path'
          slot-name: 'Production'
          package: '*.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E25E38154D2742AEBF64897CA04D1628 }}